---
- name: install certbot and rsync packages
  apt:
    name:
      - certbot  # just for case
      - rsync
    state: present
  tags: le_master_install


- name: configure ssh keys and aliases for root user to access replicas
  import_tasks: ssh.yml
  tags: le_master_ssh


- name: create replica pushing script
  template:
    src: certbot-push-replica.sh
    dest: /usr/local/sbin/certbot-push-replica.sh
    owner: root
    mode: 0700
  notify: fire first certbot push
  tags: le_master_service

- name: create replica pushing service
  template:
    src: certbot-push.service
    dest: /etc/systemd/system/certbot-push@.service
  notify: fire first certbot push
  tags: le_master_service

- name: create replica pushing timer
  template:
    src: certbot-push.timer
    dest: /etc/systemd/system/certbot-push@.timer
  notify: fire first certbot push
  tags: le_master_service

- name: enable pushing timers for all replicas (yet inactive)
  systemd:
    name: certbot-push@{{ item }}.timer
    state: stopped
    enabled: yes
    daemon_reload: yes
  loop: "{{ certbot_master_replica_hosts }}"
  notify: fire first certbot push
  tags: le_master_service

- name: create global pushing script
  copy:
    content: |
      #!/bin/bash
      echo "$(date): start pushing to all replicas" >> /var/log/letsencrypt/letsencrypt.log
      {% for host in certbot_master_replica_hosts %}
      systemctl start certbot-push@{{ host }}.timer
      {% endfor %}
    dest: /etc/letsencrypt/renewal-hooks/post/push
    owner: root
    mode: 0750
  notify: fire first certbot push
  tags: le_master_service


- name: list all present certbot-push units
  shell: systemctl list-units
                   --no-pager --no-legend
                   --all --type=service,timer
                   certbot-push@*
                   2>&1 |
        tr '@.' ',' | cut -d, -f2 | sort -u
  register: all_push_replicas
  changed_when: false
  ignore_errors: yes
  tags: le_master_cleanup

- name: remove extra certbot-push timers and services
  systemd:
    name: certbot-push@{{ item.0 }}.{{ item.1 }}
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes
  loop: "{{ all_push_replicas.stdout_lines
          | difference(certbot_master_replica_hosts)
          | product(['timer', 'service'])
          | list }}"
  tags: le_master_cleanup
...
