---
- name: ensure that .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: verify that ssh keys are configured
  assert:
    that: "certbot_replica_ssh_keys | length > 0"
    msg: "access keys not found!"

- name: install ssh keys
  copy:
    src: "{{ item }}"
    dest: ~/.ssh/
    mode: 0400
  loop: "{{ certbot_replica_ssh_keys }}"
  loop_control:
    label: "{{ item | basename }}"


- name: configure ssh aliases for certbot replica hosts
  blockinfile:
    path: ~/.ssh/config
    create: true
    mode: 0600
    block: |
      {% for host in certbot_master_replica_hosts %}
      Host {{ host }}.certbot-replica
        Hostname {{ hostvars[host].ansible_host }}
        Port {{ hostvars[host].ansible_port }}
        User {{ hostvars[host].certbot_replica_user
              | default(hostvars[host].ansible_user_id) }}
        IdentityFile ~/.ssh/{{ certbot_replica_ssh_keys
                             | first | basename }}
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        LogLevel ERROR

      {% endfor %}
    marker: "# == {mark} certbot replicas =="
    # insert before any "glob overriding" entry
    insertbefore: "^Host .*[*]"
...
